version: '3.8'
services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://database:3306/enterprise
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: enterprise
    ports:
      - "3306:3306"
